comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
codecov:
  token: 337d5992-7fda-4283-8739-95258730649d
  
